[project]
name = "odoo-addons-oca-sign"
version = "18.0.20260930.0"
dependencies = [
    "odoo-addon-agreement_sign_oca==18.0.*",
    "odoo-addon-crm_sign_oca==18.0.*",
    "odoo-addon-project_task_sign_oca==18.0.*",
    "odoo-addon-sign_oca==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
